"""icons

Revision ID: 21b00ae0a6bb
Revises: aacde0f57395
Create Date: 2018-07-29 08:58:19.699422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21b00ae0a6bb'
down_revision = 'aacde0f57395'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nonprofit', sa.Column('logo', sa.String(), nullable=True))
    op.drop_index('ix_nonprofit_photo', table_name='nonprofit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_nonprofit_photo', 'nonprofit', ['photo'], unique=False)
    op.drop_column('nonprofit', 'logo')
    # ### end Alembic commands ###
