"""phone and email

Revision ID: 3db2384567db
Revises: 8722440df954
Create Date: 2018-07-29 08:06:48.022967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3db2384567db'
down_revision = '8722440df954'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nonprofit', sa.Column('email', sa.String(), nullable=True))
    op.add_column('nonprofit', sa.Column('phone', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_nonprofit_email'), 'nonprofit', ['email'], unique=False)
    op.create_index(op.f('ix_nonprofit_phone'), 'nonprofit', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nonprofit_phone'), table_name='nonprofit')
    op.drop_index(op.f('ix_nonprofit_email'), table_name='nonprofit')
    op.drop_column('nonprofit', 'phone')
    op.drop_column('nonprofit', 'email')
    # ### end Alembic commands ###
