"""new inputs location, contact, and website

Revision ID: 8722440df954
Revises: a3955f156b35
Create Date: 2018-07-29 08:01:04.109634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8722440df954'
down_revision = 'a3955f156b35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nonprofit', sa.Column('location', sa.String(), nullable=True))
    op.add_column('nonprofit', sa.Column('website', sa.String(), nullable=True))
    op.create_index(op.f('ix_nonprofit_location'), 'nonprofit', ['location'], unique=False)
    op.create_index(op.f('ix_nonprofit_website'), 'nonprofit', ['website'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nonprofit_website'), table_name='nonprofit')
    op.drop_index(op.f('ix_nonprofit_location'), table_name='nonprofit')
    op.drop_column('nonprofit', 'website')
    op.drop_column('nonprofit', 'location')
    # ### end Alembic commands ###
