"""nonprofit

Revision ID: a3955f156b35
Revises: 
Create Date: 2018-07-28 19:27:38.653734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3955f156b35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nonprofit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nonprofit_category'), 'nonprofit', ['category'], unique=False)
    op.create_index(op.f('ix_nonprofit_description'), 'nonprofit', ['description'], unique=False)
    op.create_index(op.f('ix_nonprofit_name'), 'nonprofit', ['name'], unique=False)
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Float(precision=2), nullable=True),
    sa.Column('nonprofit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nonprofit_id'], ['nonprofit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_name'), 'item', ['name'], unique=False)
    op.create_index(op.f('ix_item_price'), 'item', ['price'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_price'), table_name='item')
    op.drop_index(op.f('ix_item_name'), table_name='item')
    op.drop_table('item')
    op.drop_index(op.f('ix_nonprofit_name'), table_name='nonprofit')
    op.drop_index(op.f('ix_nonprofit_description'), table_name='nonprofit')
    op.drop_index(op.f('ix_nonprofit_category'), table_name='nonprofit')
    op.drop_table('nonprofit')
    # ### end Alembic commands ###
